### ISSUE TITLE
Tests failed on LispWorks 7.0 32bit

### ISSUE THREAD

**Issue by fourier** [Shinmera/3d-matrices#10]
Relevant part of the log:

> ;; Summary:
> Passed:    59
> Failed:    24
> Skipped:    6
> 
> ;; Failures:
>    6/  20 tests failed in 3D-MATRICES-TEST::mat3
> The test form   (capture-error (miref3 (mat3) -1))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
> The test form   (capture-error (miref3 (mat3) 9))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
> The test form   (capture-error (mcref3 (mat3) 3 0))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
> The test form   (capture-error (miref (mat3) -1))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
> The test form   (capture-error (miref (mat3) 9))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
> The test form   (capture-error (mcref (mat3) 3 0))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
>    6/  20 tests failed in 3D-MATRICES-TEST::mat2
> The test form   (capture-error (miref2 (mat2) -1))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
> The test form   (capture-error (miref2 (mat2) 4))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
> The test form   (capture-error (mcref2 (mat2) 2 0))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
> The test form   (capture-error (miref (mat2) -1))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
> The test form   (capture-error (miref (mat2) 4))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
> The test form   (capture-error (mcref (mat2) 2 0))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
>    2/   2 tests failed in 3D-MATRICES-TEST::struct
>    6/  23 tests failed in 3D-MATRICES-TEST::matn
> 
>    6/  20 tests failed in 3D-MATRICES-TEST::mat4
> 
>    6/  23 tests failed in 3D-MATRICES-TEST::matn
> The test form   (capture-error (mirefn (matn 1 2) -1))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
> The test form   (capture-error (mirefn (matn 1 2) 2))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
> The test form   (capture-error (mcrefn (matn 1 2) 1 0))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
> The test form   (capture-error (miref (matn 1 2) -1))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
> The test form   (capture-error (miref (matn 1 2) 2))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
> The test form   (capture-error (mcref (matn 1 2) 1 0))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
>    6/  20 tests failed in 3D-MATRICES-TEST::mat4
> The test form   (capture-error (miref4 (mat4) -1))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
> The test form   (capture-error (miref4 (mat4) 16))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
> The test form   (capture-error (mcref4 (mat4) 4 0))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
> The test form   (capture-error (miref (mat4) -1))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
> The test form   (capture-error (miref (mat4) 16))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
> The test form   (capture-error (mcref (mat4) 4 0))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
>

**Comment by Shinmera** [comment]
Looks like those all boil down to LispWorks disabling bounds checks on low safety levels.

**Comment by fourier** [comment]
I see. I'll run my app I've developed on SBCL without problems on LW and report if I encounter any issues.

**Comment by Shinmera** [comment]
I'd still rather fix this so that the tests pass.

**Comment by fourier** [comment]
Thanks for the extremely quick response by the way, your library came up first in search for simple matrix libraries for CL and it worked out perfectly for me to do some geometry manipulations in CL real quick. The only complaint is to reduce a number of dependencies - like documentation should be a separate package like test as it and its dependencies has nothing to do with the matrix operations functionality.
Also auto-generated documentation for 3d-vectors is confusing, probably better just to show the pattern and dont document all auto-generated functions as it makes it hard to scroll down to find out the necessary functions. The same for matrix library, the grouping could be done for functions so one could quickly understand which transformations and matrix operations are supported.

**Comment by lovrolu** [comment]
> Also auto-generated documentation for 3d-vectors is confusing, probably better just to show the pattern and dont document all auto-generated functions as it makes it hard to scroll down to find out the necessary functions.

+1 for this. I found it very inconvenient myself but haven't gotten around to reporting it. Perhaps we should open a separate issue for that?

**Comment by Shinmera** [comment]
Documentation is a vital part of a library and all my systems nowadays depend on documentation-utils, which is tiny. This can hardly be qualified as a problem under any circumstance. I don't even depend on Alexandria, for crying out loud!

Regarding the docs, that could certainly be improved, but I don't see much of a priority for it myself. I'd rather the main README text be expanded if discoverability is bad than to somehow truncate the symbol index.

**Comment by fourier** [comment]
Yep probably but the documentation is not necessary to multiply matrices.
As for improvements all matrix-vector operations have a long history of how to group them, see for example BLAS levels, and lack of grouping in combination with huge-amount of auto-generated documentation makes it little bit difficult to search for necessary functions. But its for you to decide anyway :)

**Comment by Shinmera** [comment]
I absolutely refuse to remove docstrings from a library for any reason whatsoever. It is ridiculous to even consider doing this.

**Comment by lovrolu** [comment]
Yeah, I'm not sure that *completely* filtering them out is a good idea. I was thinking of introducing a separate section for swizzlers and condensing their description into just one "entry", a rule/grammar of sorts that describes all of them at once. In order to keep it simple and not go too nuts with the grammar, perhaps 3 separate entries can be made -- one for 2d, one for 3d and one for 4d swizzlers.

**Comment by Shinmera** [comment]
I [filtered them out for now](https://shinmera.github.io/3d-vectors/). I hope the section in the readme is explanatory enough.

**Comment by lovrolu** [comment]
Looks like the style of the documentation changed. You should regenerate the docs for `3d-matrices` as well.

**Comment by Shinmera** [comment]
Jeez you people, I'm already on it.

**Comment by fourier** [comment]
> 
> 
> I [filtered them out for now](https://shinmera.github.io/3d-vectors/). I hope the section in the readme is explanatory enough.

Now its real good!

**Comment by Shinmera** [comment]
Updated matrix docs too. Not sure why source tracking is not working for most definitions, but that's for another day.

**Comment by Shinmera** [comment]
Nevermind, fixed. Shinmera/definitions@82f36c5 and Shinmera/staple@0ee0920.

**Comment by fourier** [comment]
Now its better, still some errors:

> ;; Summary:
> Passed:    77
> Failed:     6
> Skipped:    6
> 
> ;; Failures:
>    1/   2 tests failed in 3D-MATRICES-TEST::struct
>    6/  23 tests failed in 3D-MATRICES-TEST::matn
> 
>    6/  23 tests failed in 3D-MATRICES-TEST::matn
> The test form   (capture-error (mirefn (matn 1 2) -1))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
> The test form   (capture-error (mirefn (matn 1 2) 2))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
> The test form   (capture-error (mcrefn (matn 1 2) 1 0))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
> The test form   (capture-error (miref (matn 1 2) -1))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
> The test form   (capture-error (miref (matn 1 2) 2))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
> The test form   (capture-error (mcref (matn 1 2) 1 0))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
>
