### ISSUE TITLE
mlookup->nvunit->nv/ issue

### ISSUE THREAD

**Issue by gzip4** [Shinmera/3d-matrices#2]
3d-matrices:mlookup uses 3d-vectors:nvunit which in turn uses 3d-vectors:nv/ and the latter causes the error:
_The value 0.0 is not of the expected type STRUCTURE._
in simple eval
`(mlookat (vec 0 0 0) (vec 0 0 -1) (vec 0 1 0))`

I wonder why the N-version of / operation is used there?

**Comment by Shinmera** [comment]
`nvunit` uses `nv/` because it is supposed to be modifying. `mlookat` uses `nvunit` internally to save on allocations.

I can't reproduce your error with the given code snippet on the latest version of 3d-matrices, though.

**Comment by gzip4** [comment]
please try `(nv/ (vec 5 0 0) 5)`

**Comment by Shinmera** [comment]
Works as advertised.

**Comment by gzip4** [comment]
I've updated my quicklisp, start plain lisp process but has the same error.
```
(lisp-implementation-type)
"Clozure Common Lisp"
(lisp-implementation-version)
"Version 1.11-r16635  (WindowsX8632)"

```

**Comment by Shinmera** [comment]
I'm not sure what else to tell you. I'm on the latest Git sources locally and all your test cases work just fine on both CCL and SBCL, though there haven't been any changes that should affect the operations involved in a long while anyway. I doubt my being on Linux makes any difference for this either.

**Comment by gzip4** [comment]
Linux version of CCL (16635) signals error either. Quicklisp package - 3d-vectors-20170403-git. What version of CCL you are using?

**Comment by Shinmera** [comment]
I've updated CCL to Version 1.11-r16635 (LinuxX8664) and don't get the error there either.

**Comment by Shinmera** [comment]
I've now also tested it on Windows with a clean CCL 1.11 using a download of 3d-vectors alone, with no other systems installed and your error does not reproduce.

**Comment by gzip4** [comment]
I suspect that it is X8632 version issue, Linux or Windows (not ARM). I have no access to 64-bit machine until evening.

**Comment by Shinmera** [comment]
Ah, indeed, I can reproduce your issue when I run the 32 bit version of CCL. It does look like a compiler issue. Unfortunately the code 3d-vectors produces is not pretty or easy to minimise into a simple test case, so I don't know how amiable people will be to figure this issue out.

Just as a side note: 32 bit is going to be very slow anyway, due to it needing to box even single-floats, making all operations on them rather inefficient.

**Comment by Shinmera** [comment]
Alright, managed to produce a minimal test case:
```
(let ((vec (3d-vectors::vec 5 0 0)))
           (psetf (3d-vectors::%vx3 vec) 5.0
                  (3d-vectors::%vy3 vec) 5.0))
```
The problem seems to be related to `psetf`. If you remove one of the set pairs, it works fine. If you use `setf`, it also works fine.

**Comment by Shinmera** [comment]
If you post the above snippet to the mailing list, I'd appreciate it if you could CC me.

**Comment by gzip4** [comment]
Ok.

**Comment by gzip4** [comment]
This works fine, but what's the difference?
```
(defstruct stest a b)
(let ((st (make-stest)))
  (psetf (stest-a st) 1
	 (stest-b st) 2))

```

**Comment by Shinmera** [comment]
You need the type declarations in the structure slots.

**Comment by gzip4** [comment]
This does not signal the error:
`(defstruct stest (a 0 :type fixnum) (b 0 :type fixnum))`

**Comment by Shinmera** [comment]
My guess that it's related to the boxing of floats. Fixnums fit into a single word on 32x, while single-floats do not. But I don't really know anything about the CCL internals, so that's just a wild guess.

**Comment by gzip4** [comment]
I fully agry with you.

**Comment by Shinmera** [comment]
clozure/ccl#36
