### ISSUE TITLE
Cant compile on LispWorks 32bit

### ISSUE THREAD

**Issue by fourier** [Shinmera/3d-matrices#9]
An error while trying to compile with LispWorks 7.0 32bit for Windows

> 
> ; Loading "3d-matrices"
> .
> Error: The value 9.999989S-6 of *eps* is not of type single-float when declaring its type.

**Comment by Shinmera** [comment]
Try with bddb2b7 applied

**Comment by fourier** [comment]
Thanks, this solves the load problem. I've found in LW documentation that single-float is a boxed type in LispWorks 32bit. I guess it might lead to some problems? At least tests are failed:

> ;; Summary:
> Passed:    38
> Failed:    45
> Skipped:    6
> 
> ;; Failures:
>   13/  20 tests failed in 3D-MATRICES-TEST::mat4
> The test form   (mat4)
> evaluated to    Undefined function 3d-matrices-test::|mat4| called with arguments ().
> when            mat4
> was expected to be equal under typep.
> 
> The test form   (mcopy4 (mat4))
> evaluated to    Undefined function 3d-matrices-test::|mat4| called with arguments ().
> when            mat4
> was expected to be equal under typep.
> 
> The test form   (mat4-p (mat4))
> evaluated to    Undefined function 3d-matrices-test::|mat4| called with arguments ().
> when            t
> was expected to be equal under geq.
> 
> The test form   (mat4-p (mat2))
> evaluated to    Undefined function 3d-matrices-test::|mat2| called with arguments ().
> when            ()
> was expected to be equal under geq.
> 
> The test form   (miref4 (mat4) 0)
> evaluated to    Undefined function 3d-matrices-test::|mat4| called with arguments ().
> when            0
> was expected to be equal under =.
> 
> The test form   (mcref4 (mat4) 0 0)
> evaluated to    Undefined function 3d-matrices-test::|mat4| called with arguments ().
> when            0
> was expected to be equal under =.
> 
> The test form   (mat 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
> evaluated to    (mat4 #(0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0))
> when            mat4
> was expected to be equal under typep.
> 
> The test form   (mcopy (mat4))
> evaluated to    Undefined function 3d-matrices-test::|mat4| called with arguments ().
> when            mat4
> was expected to be equal under typep.
> 
> The test form   (mat-p (mat4))
> evaluated to    Undefined function 3d-matrices-test::|mat4| called with arguments ().
> when            t
> was expected to be equal under geq.
> 
> The test form   (miref (mat4) 0)
> evaluated to    Undefined function 3d-matrices-test::|mat4| called with arguments ().
> when            0
> was expected to be equal under =.
> 
> The test form   (mcref (mat4) 0 0)
> evaluated to    Undefined function 3d-matrices-test::|mat4| called with arguments ().
> when            0
> was expected to be equal under =.
> 
> The test form   (mcols (mat4))
> evaluated to    Undefined function 3d-matrices-test::|mat4| called with arguments ().
> when            4
> was expected to be equal under =.
> 
> The test form   (mrows (mat4))
> evaluated to    Undefined function 3d-matrices-test::|mat4| called with arguments ().
> when            4
> was expected to be equal under =.
> 
>    3/   3 tests failed in 3D-MATRICES-TEST::struct
>    6/  23 tests failed in 3D-MATRICES-TEST::matn
> 
>   13/  20 tests failed in 3D-MATRICES-TEST::mat3
> 
>   13/  20 tests failed in 3D-MATRICES-TEST::mat2
> 
>    6/  23 tests failed in 3D-MATRICES-TEST::matn
> The test form   (capture-error (mirefn (matn 1 2) -1))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
> The test form   (capture-error (mirefn (matn 1 2) 2))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
> The test form   (capture-error (mcrefn (matn 1 2) 1 0))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
> The test form   (capture-error (miref (matn 1 2) -1))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
> The test form   (capture-error (miref (matn 1 2) 2))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
> The test form   (capture-error (mcref (matn 1 2) 1 0))
> evaluated to    ()
> when            error
> was expected to be equal under typep.
> 
>   13/  20 tests failed in 3D-MATRICES-TEST::mat3
> The test form   (mat3)
> evaluated to    Undefined function 3d-matrices-test::|mat3| called with arguments ().
> when            mat3
> was expected to be equal under typep.
> 
> The test form   (mcopy3 (mat3))
> evaluated to    Undefined function 3d-matrices-test::|mat3| called with arguments ().
> when            mat3
> was expected to be equal under typep.
> 
> The test form   (mat3-p (mat3))
> evaluated to    Undefined function 3d-matrices-test::|mat3| called with arguments ().
> when            t
> was expected to be equal under geq.
> 
> The test form   (mat3-p (mat4))
> evaluated to    Undefined function 3d-matrices-test::|mat4| called with arguments ().
> when            ()
> was expected to be equal under geq.
> 
> The test form   (miref3 (mat3) 0)
> evaluated to    Undefined function 3d-matrices-test::|mat3| called with arguments ().
> when            0
> was expected to be equal under =.
> 
> The test form   (mcref3 (mat3) 0 0)
> evaluated to    Undefined function 3d-matrices-test::|mat3| called with arguments ().
> when            0
> was expected to be equal under =.
> 
> The test form   (mat 0 0 0 0 0 0 0 0 0)
> evaluated to    (mat3 #(0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0))
> when            mat3
> was expected to be equal under typep.
> 
> The test form   (mcopy (mat3))
> evaluated to    Undefined function 3d-matrices-test::|mat3| called with arguments ().
> when            mat3
> was expected to be equal under typep.
> 
> The test form   (mat-p (mat3))
> evaluated to    Undefined function 3d-matrices-test::|mat3| called with arguments ().
> when            t
> was expected to be equal under geq.
> 
> The test form   (miref (mat3) 0)
> evaluated to    Undefined function 3d-matrices-test::|mat3| called with arguments ().
> when            0
> was expected to be equal under =.
> 
> The test form   (mcref (mat3) 0 0)
> evaluated to    Undefined function 3d-matrices-test::|mat3| called with arguments ().
> when            0
> was expected to be equal under =.
> 
> The test form   (mcols (mat3))
> evaluated to    Undefined function 3d-matrices-test::|mat3| called with arguments ().
> when            3
> was expected to be equal under =.
> 
> The test form   (mrows (mat3))
> evaluated to    Undefined function 3d-matrices-test::|mat3| called with arguments ().
> when            3
> was expected to be equal under =.
> 
>   13/  20 tests failed in 3D-MATRICES-TEST::mat2
> The test form   (mat2)
> evaluated to    Undefined function 3d-matrices-test::|mat2| called with arguments ().
> when            mat2
> was expected to be equal under typep.
> 
> The test form   (mcopy2 (mat2))
> evaluated to    Undefined function 3d-matrices-test::|mat2| called with arguments ().
> when            mat2
> was expected to be equal under typep.
> 
> The test form   (mat2-p (mat2))
> evaluated to    Undefined function 3d-matrices-test::|mat2| called with arguments ().
> when            t
> was expected to be equal under geq.
> 
> The test form   (mat2-p (mat3))
> evaluated to    Undefined function 3d-matrices-test::|mat3| called with arguments ().
> when            ()
> was expected to be equal under geq.
> 
> The test form   (miref2 (mat2) 0)
> evaluated to    Undefined function 3d-matrices-test::|mat2| called with arguments ().
> when            0
> was expected to be equal under =.
> 
> The test form   (mcref2 (mat2) 0 0)
> evaluated to    Undefined function 3d-matrices-test::|mat2| called with arguments ().
> when            0
> was expected to be equal under =.
> 
> The test form   (mat 0 0 0 0)
> evaluated to    (mat2 #(0.0 0.0 0.0 0.0))
> when            mat2
> was expected to be equal under typep.
> 
> The test form   (mcopy (mat2))
> evaluated to    Undefined function 3d-matrices-test::|mat2| called with arguments ().
> when            mat2
> was expected to be equal under typep.
> 
> The test form   (mat-p (mat2))
> evaluated to    Undefined function 3d-matrices-test::|mat2| called with arguments ().
> when            t
> was expected to be equal under geq.
> 
> The test form   (miref (mat2) 0)
> evaluated to    Undefined function 3d-matrices-test::|mat2| called with arguments ().
> when            0
> was expected to be equal under =.
> 
> The test form   (mcref (mat2) 0 0)
> evaluated to    Undefined function 3d-matrices-test::|mat2| called with arguments ().
> when            0
> was expected to be equal under =.
> 
> The test form   (mcols (mat2))
> evaluated to    Undefined function 3d-matrices-test::|mat2| called with arguments ().
> when            2
> was expected to be equal under =.
> 
> The test form   (mrows (mat2))
> evaluated to    Undefined function 3d-matrices-test::|mat2| called with arguments ().
> when            2
> was expected to be equal under =.
> 
> 
> The following functions are undefined:
> 3d-matrices-test::|mat4| which is referenced by top-level-form
> 3d-matrices-test::|mcopy2| which is referenced by top-level-form
> 3d-matrices-test::|miref4| which is referenced by top-level-form
> 3d-matrices-test::|mat2| which is referenced by top-level-form
> 3d-matrices-test::|miref3| which is referenced by top-level-form
> 3d-matrices-test::|mcref2| which is referenced by top-level-form
> 3d-matrices-test::|mat3| which is referenced by top-level-form
> 3d-matrices-test::|mat4-p| which is referenced by top-level-form
> 3d-matrices-test::|mat3-p| which is referenced by top-level-form
> 3d-matrices-test::|miref2| which is referenced by top-level-form
> 3d-matrices-test::|mcopy4| which is referenced by top-level-form
> 3d-matrices-test::|mcopy3| which is referenced by top-level-form
> 3d-matrices-test::|mat2-p| which is referenced by top-level-form
> 3d-matrices-test::|mcref4| which is referenced by top-level-form
> 3d-matrices-test::|mcref3| which is referenced by top-level-form
> t
>

**Comment by Shinmera** [comment]
You seem to be using a non-standard readtable case. This is not supported.

**Comment by Shinmera** [comment]
Hm, or a non-standard print-case. I'll see about that at least.

**Comment by fourier** [comment]
Yes its a print-case, I have (setf *print-case* :downcase)

**Comment by Shinmera** [comment]
Should be fixed via shinmera/3d-vectors#74b2b6b and 7e69dbd

**Comment by fourier** [comment]
Thanks! 3d-vectors tested without problems, with 3d matrices still some tests failed. I'll report separate issue on it
